### ISSUE TITLE
Not working due to 404

### ISSUE THREAD

**Issue by ojonasplima** [jameslieu/howlongtobeat#1]
Due to error on the HTTP post sender, getting 404 response as showed below.
![error1](https://user-images.githubusercontent.com/86431106/180895606-35e97a19-3232-4cd6-bdc8-efb500cd5f21.PNG)
![error2](https://user-images.githubusercontent.com/86431106/180895608-04f4a117-45dd-4c1c-b8f7-daa53a7187c7.PNG)

**Comment by ojonasplima** [comment]
Fixed.

**Comment by jameslieu** [comment]
Thank you Jonas! I've merged and published your changes to `1.0.3`. Looks like its working!

Have you got a Twitter handle? I want to give you a shout out. Here's mine [J_Lieu](https://twitter.com/J_Lieu)

Thanks again
